CLASS zjmn_cl_19_honda_logali DEFINITION ABSTRACT INHERITING FROM zjmn_cl_18_moto_logali
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
    METHODS set_model ABSTRACT EXPORTING ev_model TYPE string.

  PRIVATE SECTION.
ENDCLASS.



CLASS zjmn_cl_19_honda_logali IMPLEMENTATION.
ENDCLASS.
