CLASS zjmn_cl_06_storage_logali DEFINITION INHERITING FROM  zjmn_cl_05_plant_logali
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zjmn_cl_06_storage_logali IMPLEMENTATION.
ENDCLASS.
